name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Display the path
        run: echo ${env:PATH}
        shell: pwsh
      - name: Build Win 1
        shell: pwsh
        run: build_win
      - name: Build Win 2
        shell: pwsh
        if: startsWith(matrix.os, 'windows')
        env:
          NODE_ENV: production
        run: |
          .\build_win.ps1
